import 'package:flutter/material.dart';
import 'package:geolocator/geolocator.dart';
import 'package:audioplayers/audioplayers.dart';

//Code partially generated by ChatGPT 3.5, OpenAI 2024. 

class LocationTrackerWidget extends StatefulWidget {
  @override
  _LocationTrackerWidgetState createState() => _LocationTrackerWidgetState();
}

class _LocationTrackerWidgetState extends State<LocationTrackerWidget> {
  late Position _currentPosition;
  late Position target;
  AudioPlayer audioPlayer = AudioPlayer();


  @override
  void initState() {
    super.initState();
    _initLocationTracking();
  }

  void _initLocationTracking() {
    Geolocator.getPositionStream().listen((Position position) {
      setState(() {
        _currentPosition = position;
        target = position;
      });

      // Check if the current position is close to the target coordinates
      if (_isCloseToTarget()) {
        // Play audio when close to the target coordinates
        _playAudio();
      }
    });
  }

  bool _isCloseToTarget() {
    double dist = ((_currentPosition.latitude - target.latitude) * (_currentPosition.latitude - target.latitude))+
    ((_currentPosition.longitude - target.longitude) * (_currentPosition.longitude - target.longitude));
    if (dist < 0.00000001) {
      return true;
    }
    return false;
  }

  void _playAudio() async {
    String audioUrl = 'https://www.youtube.com/watch?v=PAm8lPx9KHc&ab_channel=nari';
    await audioPlayer.play(UrlSource(audioUrl));
  }

  @override
  void dispose() {
    audioPlayer.dispose(); // Dispose of the audio player when the widget is disposed
    super.dispose();
  }

  @override
  Widget build(BuildContext context){
    return Scaffold();
  }
}

void main() {
  runApp(MaterialApp(
    home: LocationTrackerWidget(),
  ));
}
