import 'package:flutter/material.dart';
import 'package:geolocator/geolocator.dart';
import 'package:audioplayers/audioplayers.dart';

//Code partially generated by ChatGPT 3.5, OpenAI 2024. 

class LocationTrackerWidget extends StatefulWidget {
  @override
  _LocationTrackerWidgetState createState() => _LocationTrackerWidgetState();
}

class _LocationTrackerWidgetState extends State<LocationTrackerWidget> {
  late Position _currentPosition;
  late Position target;
  AudioPlayer audioPlayer = AudioPlayer();


  @override
  void initState() {
    super.initState();
    _initLocationTracking();
    target = target;
  }

  void _initLocationTracking() {
    Geolocator.getPositionStream().listen((Position position) {
      setState(() {
        _currentPosition = position;
      });

      // Check if the current position is close to the target coordinates
      if (_isCloseToTarget()) {
        // Play audio when close to the target coordinates
        _playAudio();
      }
    });
  }

  // Function to check if the current position is close to target coordinates
  bool _isCloseToTarget() {
    double dist = ((_currentPosition.latitude - target.latitude) * (_currentPosition.latitude - target.latitude))+
    ((_currentPosition.longitude - target.longitude) * (_currentPosition.longitude - target.longitude));
    if (dist < 0.00001) {
      return true;
    }
    return false;
  }

  // Function to play audio
  void _playAudio() async {
    String audioUrl = 'https://example.com/audio.mp3'; // Replace with your audio file URL
    int result = await audioPlayer.play(audioUrl, isLocal: false);

    if (result == 1) {
      print('Audio played successfully');
    } else {
      print('Error playing audio');
    }
  }


  @override
  void dispose() {
    audioPlayer.dispose(); // Dispose of the audio player when the widget is disposed
    super.dispose();
  }
}

void main() {
  runApp(MaterialApp(
    home: LocationTrackerWidget(),
  ));
}
